dss:
  threshold: 127
  segmentation:
    line:
      - n_splits: 20
        line_start_splits: 10
        start_lookahead: 50
        chunk_lookahead: 40
        expected_line_height: 200
        cc_min_a: 500
        cc_max_a: 100000
      - start_fraction: 0.25
        step_fraction: 0.017
        cc_min_a: 500
        cc_max_a: 100000
    word:
      - max_angle: 20
        min_angle: -20
        angle_step: 1
        min_nonzero_px: 100
        min_consec: 20
  classification:
    window:
      size: !!python/tuple [71, 40]
      hop_size: 10
      channels: 1
iam:
  threshold: 192
  segmentation:
    word:
      - max_angle: 6
        min_angle: -20
        angle_step: 2
        min_nonzero_px: 100
        min_consec: 28
  classification:
    window:
      size: !!python/tuple [71, 71]
      hop_size: 20
      channels: 3