dss:
  segmentation:
    TestSegmentation:
      - x: 0
        y: 3
      - x: 0
        y: 2
  classification:
    TestClassifier: # Parameters for the TestClassifier class listed in /dss/classification/TestClassifier.py
      - i: 0
        j: 2
      - i: 3
        j: 2